### ISSUE TITLE
Improve static page

### ISSUE THREAD

**Issue by alegaleone** [mattiapv/TurboBot#5]

**Comment by mattiapv** [comment]
Create a user friendly chatbox page.

**Comment by mattiapv** [comment]
Ogni messaggio mandato e scritto viene visualizzato come un nuovo elemento di una lista. Creare un <div> principale della chat e con jQuery creare nuovi <div> per ogni messaggio. Migliorare la grafica

**Comment by mattiapv** [comment]
Migliorare la grafica
